
project_id = "amvkehblgbxehjhehydk"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[analytics]
enabled = false

[vector]
enabled = true
port = 54327

[functions]
[functions.telegram-upload]
verify_jwt = false
[functions.telegram-file]
verify_jwt = false
[functions.telegram-file-search]
verify_jwt = false
