
project_id = "amvkehblgbxehjhehydk"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true

[realtime]
enabled = true

[storage]
enabled = true

[functions]
[functions.cloudstream-utils]
verify_jwt = false
