// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://amvkehblgbxehjhehydk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtdmtlaGJsZ2J4ZWhqaGVoeWRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4NjQ5OTAsImV4cCI6MjA1ODQ0MDk5MH0.f_Xoar3q8B0Oyh86b-zOr-SxYpnTMNZHj4B0NwlIMH8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);